#bank.csv

In [4]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/bank.csv'
df = pd.read_csv(path)
df.head(20)

   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0   30;"unemployed";"married";"primary";"no";1787;...
1   33;"services";"married";"secondary";"no";4789;...
2   35;"management";"single";"tertiary";"no";1350;...
3   30;"management";"married";"tertiary";"no";1476...
4   59;"blue-collar";"married";"secondary";"no";0;...
5   35;"management";"single";"tertiary";"no";747;"...
6   36;"self-employed";"married";"tertiary";"no";3...
7   39;"technician";"married";"secondary";"no";147...
8   41;"entrepreneur";"married";"tertiary";"no";22...
9   43;"services";"married";"primary";"no";-88;"ye...
10  39;"services";"married";"secondary";"no";9374;...
11  43;"admin.";"married";"secondary";"no";264;"ye...
12  36;"technician";"married";"tertiary";"no";1109...
13  20;"student";"single";"secondary";"no";502;"no...
14  31;"blue-collar";"married";"secondary";"no";36...
15  40;"management";"married";"tertiary";"no";194;...
16  56;"technician";"married";"secondary";"no";407...
17  37;"admin.";"single";"tertiary";"no";2317;"yes...
18  25;"blue-collar";"single";"primary";"no";-221;...
19  31;"services";"married";"secondary";"no";132;"...

In [5]:
df.dtypes

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"    object
dtype: object

In [6]:
df.describe()

       age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
count                                                4521
unique                                               4521
top     30;"unemployed";"married";"primary";"no";1787;...
freq                                                    1

In [7]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"    non-numeric -> consider encoding
dtype: object