#diabetes_dataset.csv

In [1]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/diabetes_dataset.csv'
df = pd.read_csv(path)
df.head(20)

,year,gender,age,location,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,smoking_history,bmi,hbA1c_level,blood_glucose_level,diabetes
0,2020,Female,32.0,Alabama,0,0,0,0,1,0,0,never,27.32,5.0,100,0
1,2015,Female,29.0,Alabama,0,1,0,0,0,0,0,never,19.95,5.0,90,0
2,2015,Male,18.0,Alabama,0,0,0,0,1,0,0,never,23.76,4.8,160,0
3,2015,Male,41.0,Alabama,0,0,1,0,0,0,0,never,27.32,4.0,159,0
4,2016,Female,52.0,Alabama,1,0,0,0,0,0,0,never,23.75,6.5,90,0
5,2016,Male,66.0,Alabama,0,0,1,0,0,0,0,not current,27.32,5.7,159,0
6,2015,Female,49.0,Alabama,0,0,1,0,0,0,0,current,24.34,5.7,80,0
7,2016,Female,15.0,Alabama,0,0,0,0,1,0,0,No Info,20.98,5.0,155,0
8,2016,Male,51.0,Alabama,1,0,0,0,0,0,0,never,38.14,6.0,100,0
9,2015,Male,42.0,Alabama,0,0,1,0,0,0,0,No Info,27.32,5.7,160,0
10,2016,Male,15.0,Alabama,1,0,0,0,0,0,0,No Info,19.15,6.6,200,0
11,2016,Female,53.0,Alabama,0,0,1,0,0,0,0,never,34.30,6.6,155,0
12,2015,Female,3.0,Alabama,1,0,0,0,0,0,0,No Info,20.28,3.5,159,0
13,2016,Female,40.0,Alabama,0,0,0,1,0,0,0,never,27.63,6.5,126,0
14,2016,Female,64.0,Alabama,0,0,0,0,1,0,0,ever,49.27,8.2,140,1
15,2015,Female,23.0,Alabama,0,0,1,0,0,0,0,never,27.32,6.0,140,0
16,2015,Female,2.0,Alabama,0,1,0,0,0,0,0,never,27.32,3.5,155,0
17,2015,Male,80.0,Alabama,0,0,0,0,1,0,0,No Info,27.32,6.0,130,0
18,2016,Female,12.0,Alabama,0,0,0,1,0,0,0,never,20.78,6.5,130,0
19,2015,Female,50.0,Alabama,0,1,0,0,0,0,0,never,26.39,6.6,158,0

In [2]:
df.dtypes

year                      int64
gender                   object
age                     float64
location                 object
race:AfricanAmerican      int64
race:Asian                int64
race:Caucasian            int64
race:Hispanic             int64
race:Other                int64
hypertension              int64
heart_disease             int64
smoking_history          object
bmi                     float64
hbA1c_level             float64
blood_glucose_level       int64
diabetes                  int64
dtype: object

In [3]:
df.describe()

,year,age,race:AfricanAmerican,race:Asian,race:Caucasian,race:Hispanic,race:Other,hypertension,heart_disease,bmi,hbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2018.360820,41.885856,0.202230,0.200150,0.198760,0.19888,0.199980,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,1.345239,22.516840,0.401665,0.400114,0.399069,0.39916,0.399987,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,2015.000000,0.080000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,2019.000000,24.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,2019.000000,43.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,2019.000000,60.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,2022.000000,80.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [4]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

year                       2015-2022 -> consider scaling
gender                  non-numeric -> consider encoding
age                        0.08-80.0 -> consider scaling
location                non-numeric -> consider encoding
race:AfricanAmerican                     0–1 - normalize
race:Asian                               0–1 - normalize
race:Caucasian                           0–1 - normalize
race:Hispanic                            0–1 - normalize
race:Other                               0–1 - normalize
hypertension                             0–1 - normalize
heart_disease                            0–1 - normalize
smoking_history         non-numeric -> consider encoding
bmi                      10.01-95.69 -> consider scaling
hbA1c_level                  3.5-9.0 -> consider scaling
blood_glucose_level           80-300 -> consider scaling
diabetes                                 0–1 - normalize
dtype: object