#Finance_data.csv

In [2]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/Finance_data.csv'
df = pd.read_csv(path)
df.head(20)

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet
5,Female,24,No,7,5,4,6,3,1,2,...,1-3 years,Daily,30%-40%,Mutual Fund,Retirement Plan,Liquidity,Fund Diversification,Safe Investment,Risk Free,Internet
6,Female,27,Yes,3,6,4,2,5,1,7,...,3-5 years,Monthly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,High Interest Rates,Financial Consultants
7,Male,21,Yes,2,3,7,4,6,1,5,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
8,Male,35,Yes,2,4,7,5,3,1,6,...,1-3 years,Weekly,20%-30%,Equity,Retirement Plan,Capital Appreciation,Fund Diversification,Safe Investment,Fixed Returns,Television
9,Male,31,Yes,1,3,7,4,5,2,6,...,3-5 years,Monthly,30%-40%,Fixed Deposits,Retirement Plan,Capital Appreciation,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines
10,Female,35,Yes,2,4,7,5,3,1,6,...,3-5 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Financial Consultants
11,Male,29,Yes,2,5,7,6,3,1,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Fund Diversification,Assured Returns,Fixed Returns,Financial Consultants
12,Female,21,No,1,2,3,4,5,6,7,...,1-3 years,Weekly,20%-30%,Mutual Fund,Education,Dividend,Better Returns,Safe Investment,Risk Free,Internet
13,Female,28,Yes,2,3,7,4,5,1,6,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Fund Diversification,Assured Returns,Risk Free,Newspapers and Magazines
14,Female,25,Yes,2,3,7,5,4,1,6,...,1-3 years,Monthly,20%-30%,Fixed Deposits,Health Care,Dividend,Better Returns,Assured Returns,Risk Free,Financial Consultants
15,Male,27,Yes,2,3,7,5,4,1,6,...,1-3 years,Monthly,20%-30%,Mutual Fund,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Risk Free,Newspapers and Magazines
16,Female,28,Yes,3,2,7,5,4,1,6,...,1-3 years,Monthly,20%-30%,Fixed Deposits,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Risk Free,Television
17,Male,27,Yes,3,2,7,4,5,1,6,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Financial Consultants
18,Male,29,Yes,3,2,7,4,5,1,6,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
19,Male,26,Yes,3,4,6,5,1,2,7,...,3-5 years,Monthly,20%-30%,Fixed Deposits,Health Care,Capital Appreciation,Fund Diversification,Assured Returns,Risk Free,Newspapers and Magazines

In [3]:
df.dtypes

gender                               object
age                                   int64
Investment_Avenues                   object
Mutual_Funds                          int64
Equity_Market                         int64
Debentures                            int64
Government_Bonds                      int64
Fixed_Deposits                        int64
PPF                                   int64
Gold                                  int64
Stock_Marktet                        object
Factor                               object
Objective                            object
Purpose                              object
Duration                             object
Invest_Monitor                       object
Expect                               object
Avenue                               object
What are your savings objectives?    object
Reason_Equity                        object
Reason_Mutual                        object
Reason_Bonds                         object
Reason_FD                            object
Source                               object
dtype: object

In [4]:
df.describe()

,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,27.800000,2.550000,3.475000,5.750000,4.650000,3.575000,2.025000,5.975000
std,3.560467,1.197219,1.131994,1.675617,1.369072,1.795828,1.609069,1.143263
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,25.750000,2.000000,3.000000,5.000000,4.000000,2.750000,1.000000,6.000000
50%,27.000000,2.000000,4.000000,6.500000,5.000000,3.500000,1.000000,6.000000
75%,30.000000,3.000000,4.000000,7.000000,5.000000,5.000000,2.250000,7.000000
max,35.000000,7.000000,6.000000,7.000000,7.000000,7.000000,6.000000,7.000000

In [5]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

gender                               non-numeric -> consider encoding
age                                         21-35 -> consider scaling
Investment_Avenues                   non-numeric -> consider encoding
Mutual_Funds                                  1-7 -> consider scaling
Equity_Market                                 1-6 -> consider scaling
Debentures                                    1-7 -> consider scaling
Government_Bonds                              1-7 -> consider scaling
Fixed_Deposits                                1-7 -> consider scaling
PPF                                           1-6 -> consider scaling
Gold                                          2-7 -> consider scaling
Stock_Marktet                        non-numeric -> consider encoding
Factor                               non-numeric -> consider encoding
Objective                            non-numeric -> consider encoding
Purpose                              non-numeric -> consider encoding
Duration                             non-numeric -> consider encoding
Invest_Monitor                       non-numeric -> consider encoding
Expect                               non-numeric -> consider encoding
Avenue                               non-numeric -> consider encoding
What are your savings objectives?    non-numeric -> consider encoding
Reason_Equity                        non-numeric -> consider encoding
Reason_Mutual                        non-numeric -> consider encoding
Reason_Bonds                         non-numeric -> consider encoding
Reason_FD                            non-numeric -> consider encoding
Source                               non-numeric -> consider encoding
dtype: object