## Using 10 datasets from the health_disease_prediction.csv file

In [1]:
import numpy as np
import pandas as pd
path ='/content/drive/MyDrive/Durgesh(testing)/Data augmentation/26 05 2025/health_disease_prediction.csv'
df = pd.read_csv(path)
df.head(10)

   PatientID  Age  BMI  BloodPressure  SugarLevel  HeartRate  Disease
0     100001   75   34            121         178         89        0
1     100002   63   23            135         168        112        0
2     100003   84   37            108          90         68        1
3     100004   71   32             98         183        105        0
4     100005   85   19            100         127         57        1
5     100006   42   34            143         151        112        1
6     100007   55   39            122          89         58        0
7     100008   37   25            142         112        100        0
8     100009   78   36            150         104        114        1
9     100010   78   34            100         157         60        0

finding how many datatypes will be there.

In [2]:
df.dtypes

PatientID        int64
Age              int64
BMI              int64
BloodPressure    int64
SugarLevel       int64
HeartRate        int64
Disease          int64
dtype: object

#Summary of data types and non-null values for each column.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   PatientID      100000 non-null  int64
 1   Age            100000 non-null  int64
 2   BMI            100000 non-null  int64
 3   BloodPressure  100000 non-null  int64
 4   SugarLevel     100000 non-null  int64
 5   HeartRate      100000 non-null  int64
 6   Disease        100000 non-null  int64
dtypes: int64(7)
memory usage: 5.3 MB

descriptive analysis of the given data

In [ ]:
df.describe()

,PatientID,Age,BMI,BloodPressure,SugarLevel,HeartRate,Disease
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,150000.500000,53.453310,28.737410,134.479690,134.578870,84.368530,0.299250
std,28867.657797,20.799799,6.207365,26.000401,37.537321,20.174067,0.457932
min,100001.000000,18.000000,18.000000,90.000000,70.000000,50.000000,0.000000
25%,125000.750000,35.000000,23.000000,112.000000,102.000000,67.000000,0.000000
50%,150000.500000,53.000000,29.000000,134.000000,135.000000,84.000000,0.000000
75%,175000.250000,71.000000,34.000000,157.000000,167.000000,102.000000,1.000000
max,200000.000000,89.000000,39.000000,179.000000,199.000000,119.000000,1.000000

#Value Range classificatio

In [ ]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
        print('value range classification:')
df.apply(classify_ranges)

PatientID        100001-200000 -> consider scaling
Age                      18-89 -> consider scaling
BMI                      18-39 -> consider scaling
BloodPressure           90-179 -> consider scaling
SugarLevel              70-199 -> consider scaling
HeartRate               50-119 -> consider scaling
Disease                            0–1 - normalize
dtype: object