#insurence.csv

In [2]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/Insurance.csv'
df = pd.read_csv(path)
df.head(20)

    age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
5    31  female  25.740         0     no  southeast   3756.62160
6    46  female  33.440         1     no  southeast   8240.58960
7    37  female  27.740         3     no  northwest   7281.50560
8    37    male  29.830         2     no  northeast   6406.41070
9    60  female  25.840         0     no  northwest  28923.13692
10   25    male  26.220         0     no  northeast   2721.32080
11   62  female  26.290         0    yes  southeast  27808.72510
12   23    male  34.400         0     no  southwest   1826.84300
13   56  female  39.820         0     no  southeast  11090.71780
14   27    male  42.130         0    yes  southeast  39611.75770
15   19    male  24.600         1     no  southwest   1837.23700
16   52  female  30.780         1     no  northeast  10797.33620
17   23    male  23.845         0     no  northeast   2395.17155
18   56    male  40.300         0     no  southwest  10602.38500
19   30    male  35.300         0    yes  southwest  36837.46700

In [3]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [4]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [5]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

age                         18-64 -> consider scaling
sex                  non-numeric -> consider encoding
bmi                   15.96-53.13 -> consider scaling
children                      0-5 -> consider scaling
smoker               non-numeric -> consider encoding
region               non-numeric -> consider encoding
charges     1121.8739-63770.42801 -> consider scaling
dtype: object