In [6]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/Iris.csv'
df = pd.read_csv(path)
df.head(20)

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa

In [7]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [8]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

sepal_length         4.3-7.9 -> consider scaling
sepal_width          2.0-4.4 -> consider scaling
petal_length         1.0-6.9 -> consider scaling
petal_width          0.1-2.5 -> consider scaling
species         non-numeric -> consider encoding
dtype: object