#Product.csv

In [7]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/Product.csv'
df = pd.read_csv(path)
df.head(20)

,Product ID,Product Title,Merchant ID,Cluster ID,Cluster Label,Category ID,Category Label
0,1,apple iphone 8 plus 64gb silver,1,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
1,2,apple iphone 8 plus 64 gb spacegrau,2,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
3,4,apple iphone 8 plus 64gb space grey,4,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
5,6,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,6,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
6,7,apple iphone 8 plus 64 gb space grey,7,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
7,8,apple iphone 8 plus 64gb space grey,8,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
8,9,apple iphone 8 plus 64gb space grey,9,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
9,10,apple iphone 8 plus 64gb space grey,10,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
10,11,apple iphone 8 plus 5.5 single sim 4g 64gb silver,11,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
11,12,sim free iphone 8 plus 64gb by apple space grey,12,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
12,13,apple iphone 8 plus 64gb gold smartphone,13,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
13,14,apple iphone 8 plus 5.5 single sim 4g 64gb grey,14,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
14,15,apple iphone 8 plus silver 5.5 64gb 4g unlocke...,15,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
15,16,apple iphone 8 plus 64 gb silver,16,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
16,17,apple iphone 8 plus 64gb silver unlocked,17,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
17,18,apple iphone 8 plus 14 cm 5.5 64 gb 12 mp ios ...,18,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
18,19,iphone 8 plus sim free water dust resistant 64...,19,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
19,20,iphone 8 plus 64gb space grey,20,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones

In [8]:
df.dtypes

Product ID          int64
Product Title      object
 Merchant ID        int64
 Cluster ID         int64
 Cluster Label     object
 Category ID        int64
 Category Label    object
dtype: object

In [9]:
df.describe()

         Product ID   Merchant ID    Cluster ID   Category ID
count  35311.000000  35311.000000  35311.000000  35311.000000
mean   26150.800176    120.501883  30110.687633   2618.142930
std    13498.191220    117.045557  18410.265642      3.600708
min        1.000000      1.000000      1.000000   2612.000000
25%    14958.500000     17.000000   6123.000000   2615.000000
50%    27614.000000     75.000000  40630.000000   2619.000000
75%    37508.500000    253.000000  44059.000000   2622.000000
max    47358.000000    371.000000  47525.000000   2623.000000

In [10]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

Product ID              1-47358 -> consider scaling
Product Title      non-numeric -> consider encoding
 Merchant ID              1-371 -> consider scaling
 Cluster ID             1-47525 -> consider scaling
 Cluster Label     non-numeric -> consider encoding
 Category ID          2612-2623 -> consider scaling
 Category Label    non-numeric -> consider encoding
dtype: object