In [1]:
#Students Dropout and Success (1).csv

In [2]:
import pandas as pd
path = '/content/drive/MyDrive/Durgesh(testing)/Data augmentation/27 05 2025/Students Dropout and Success (1).csv'
df = pd.read_csv(path)
df.head(20)

   Marital status;Application mode;Application order;Course;"Daytime/evening attendance\t";Previous qualification;Previous qualification (grade);Nacionality;Mother's qualification;Father's qualification;Mother's occupation;Father's occupation;Admission grade;Displaced;Educational special needs;Debtor;Tuition fees up to date;Gender;Scholarship holder;Age at enrollment;International;Curricular units 1st sem (credited);Curricular units 1st sem (enrolled);Curricular units 1st sem (evaluations);Curricular units 1st sem (approved);Curricular units 1st sem (grade);Curricular units 1st sem (without evaluations);Curricular units 2nd sem (credited);Curricular units 2nd sem (enrolled);Curricular units 2nd sem (evaluations);Curricular units 2nd sem (approved);Curricular units 2nd sem (grade);Curricular units 2nd sem (without evaluations);Unemployment rate;Inflation rate;GDP;Target
0   1;17;5;171;1;1;122.0;1;19;12;5;9;127.3;1;0;0;1...
1   1;15;1;9254;1;1;160.0;1;1;3;3;3;142.5;1;0;0;0;...
2   1;1;5;9070;1;1;122.0;1;37;37;9;9;124.8;1;0;0;0...
3   1;17;2;9773;1;1;122.0;1;38;37;5;3;119.6;1;0;0;...
4   2;39;1;8014;0;1;100.0;1;37;38;9;9;141.5;0;0;0;...
5   2;39;1;9991;0;19;133.1;1;37;37;9;7;114.8;0;0;1...
6   1;1;1;9500;1;1;142.0;1;19;38;7;10;128.4;1;0;0;...
7   1;18;4;9254;1;1;119.0;1;37;37;9;9;113.1;1;0;0;...
8   1;1;3;9238;1;1;137.0;62;1;1;9;9;129.3;0;0;0;1;...
9   1;1;1;9238;1;1;138.0;1;1;19;4;7;123.0;1;0;1;0;...
10  1;1;1;9670;1;1;139.0;1;38;19;5;7;130.6;1;0;0;1...
11  1;1;1;9500;1;1;136.0;1;19;38;9;9;119.3;1;0;0;1...
12  1;1;2;9853;1;1;133.0;1;19;37;4;9;130.2;1;0;0;1...
13  1;53;1;9254;1;42;110.0;1;1;1;4;7;111.8;1;0;0;1...
14  1;1;1;9085;1;1;149.0;1;38;37;5;5;137.1;1;0;0;1...
15  1;1;1;9773;1;1;127.0;1;19;37;9;3;120.7;1;0;0;1...
16  1;18;1;9238;1;1;137.0;1;19;38;5;8;137.4;1;0;0;...
17  1;17;2;9500;1;1;135.0;1;19;1;5;4;127.3;1;0;0;1...
18  1;1;1;9130;1;1;137.0;1;3;19;3;5;136.3;1;0;0;1;...
19  1;1;1;9853;1;1;140.0;1;19;19;7;7;124.6;1;0;0;1...

In [3]:
df.dtypes

Marital status;Application mode;Application order;Course;"Daytime/evening attendance\t";Previous qualification;Previous qualification (grade);Nacionality;Mother's qualification;Father's qualification;Mother's occupation;Father's occupation;Admission grade;Displaced;Educational special needs;Debtor;Tuition fees up to date;Gender;Scholarship holder;Age at enrollment;International;Curricular units 1st sem (credited);Curricular units 1st sem (enrolled);Curricular units 1st sem (evaluations);Curricular units 1st sem (approved);Curricular units 1st sem (grade);Curricular units 1st sem (without evaluations);Curricular units 2nd sem (credited);Curricular units 2nd sem (enrolled);Curricular units 2nd sem (evaluations);Curricular units 2nd sem (approved);Curricular units 2nd sem (grade);Curricular units 2nd sem (without evaluations);Unemployment rate;Inflation rate;GDP;Target    object
dtype: object

In [4]:
df.describe()

       Marital status;Application mode;Application order;Course;"Daytime/evening attendance\t";Previous qualification;Previous qualification (grade);Nacionality;Mother's qualification;Father's qualification;Mother's occupation;Father's occupation;Admission grade;Displaced;Educational special needs;Debtor;Tuition fees up to date;Gender;Scholarship holder;Age at enrollment;International;Curricular units 1st sem (credited);Curricular units 1st sem (enrolled);Curricular units 1st sem (evaluations);Curricular units 1st sem (approved);Curricular units 1st sem (grade);Curricular units 1st sem (without evaluations);Curricular units 2nd sem (credited);Curricular units 2nd sem (enrolled);Curricular units 2nd sem (evaluations);Curricular units 2nd sem (approved);Curricular units 2nd sem (grade);Curricular units 2nd sem (without evaluations);Unemployment rate;Inflation rate;GDP;Target
count                                                4424
unique                                               4424
top     1;10;1;9773;1;1;152.0;22;38;37;5;9;152.0;1;0;0...
freq                                                    1

In [5]:
def classify_ranges(series):
    if pd.api.types.is_numeric_dtype(series):
        min = series.min()
        max = series.max()
        if min == 1 and max == 1:
            return "1 -> refine"
        elif 0 <= min and max <= 1:
            return "0–1 - normalize"
        else:
            return f"{min}-{max} -> consider scaling"
    else:
        return "non-numeric -> consider encoding"
print('value range classification:')
df.apply(classify_ranges)

value range classification:

Marital status;Application mode;Application order;Course;"Daytime/evening attendance\t";Previous qualification;Previous qualification (grade);Nacionality;Mother's qualification;Father's qualification;Mother's occupation;Father's occupation;Admission grade;Displaced;Educational special needs;Debtor;Tuition fees up to date;Gender;Scholarship holder;Age at enrollment;International;Curricular units 1st sem (credited);Curricular units 1st sem (enrolled);Curricular units 1st sem (evaluations);Curricular units 1st sem (approved);Curricular units 1st sem (grade);Curricular units 1st sem (without evaluations);Curricular units 2nd sem (credited);Curricular units 2nd sem (enrolled);Curricular units 2nd sem (evaluations);Curricular units 2nd sem (approved);Curricular units 2nd sem (grade);Curricular units 2nd sem (without evaluations);Unemployment rate;Inflation rate;GDP;Target    non-numeric -> consider encoding
dtype: object